Exception on /api/submit [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Exception in submit: insert or update on table "submission" violates foreign key constraint "submission_teamid_fkey"
DETAIL:  Key (team_id)=(296a209e-66b9-4d38-98b5-669acb6f8419) is not present in table "team".
CONTEXT:  SQL statement "INSERT INTO SUBMISSION (team_id) VALUES (vid) RETURNING submission_id"
PL/pgSQL function submit_code_file(character varying,uuid) line 5 at SQL statement

Exception on /api/submit [POST]
Traceback (most recent call last):
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1519, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1538, in finalize_request
    response = self.make_response(rv)
  File "/home/acm/.local/lib/python3.8/site-packages/flask/app.py", line 1730, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a int.
Registered team at IP 172.25.236.127
Recieved submission from f2252b84-0bc8-48de-a847-dd822925ddb2 at IP 172.25.236.127
ratelimit 1 per 1 minute (172.25.236.127) exceeded at endpoint: submit_file
